# This is a basic workflow that is manually triggered

name: Replace Cohort Number
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      COHORT_NUMBER:
        # Label for the UI
        description: 'Current Cohort Number'
        # Default value if no value is explicitly provided
        default: 'x'
        # Input has to be provided for the workflow to run
        required: true
      GITHUB_ORG:
        # Label for the UI
        description: 'GitHub Organisation link'
        # Default value if no value is explicitly provided
        default: 'https://github.com/fac-x'
        # Input has to be provided for the workflow to run
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  set-cohort-number:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # sets up node and checks out the repo
    - uses: actions/setup-node@v3.3.0
    - uses: actions/checkout@v3
    - name: Find and replace cohort number
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "${cohort-number}"
        replace: "${{ inputs.COHORT_NUMBER }}"
        exclude: ".github/**"
        regex: false
    - name: Find and replace github org
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "${github-org}"
        replace: "${{ inputs.GITHUB_ORG }}"
        exclude: ".github/**"
        regex: false
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Update cohort number and github org placeholders"
        commit-message:  "Update cohort number and github org placeholders"
        
    
      
